### ISSUE TITLE
Month update, event dot update

### ISSUE THREAD

**Issue by marcpages** [Mozharovsky/CVCalendar#14]
Hi,
Is there any way to update days dot marker before loading a month?

Thanks!

**Comment by Mozharovsky** [comment]
Hello @marcpages, 

Could you please more explicit? I don't completely understand the thing you're talking about. 

Regards, 
Eugene

**Comment by marcpages** [comment]
When you swipe right or left to change the month view, is there any way to update the day event dot marker before loading the next month? I mean a delegated function called before the month is loaded.

Thanks

**Comment by Mozharovsky** [comment]
Dot markers are being created at the time of MonthView setup. I could provide a method notifying when a dot marker is being created. But I still don't understand what you're trying to do to be capable of predicting the best way of designing the feature. 

Thus it would have a sense if you provided me with an idea you want to reach.

**Comment by marcpages** [comment]
I've this function:
```
func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool {
        let day : Int? = dayView.date?.day
        if contains(self.daysWithDotArray, day!) {
            return true
        } else {
            return false
        }
    }
```
and I want to update `daysWithDotArray` when you change month and before any day is created.

Thanks

**Comment by Mozharovsky** [comment]
Hello @marcpages, 

Sorry for not replying for so long. It isn't that clear still. As well as I understand, you have an array with days you're planning to mark with dots. So if there is something wrong with a practical month you can simply get the month with a CVDate instance and then check whether it's optimal for your purpose or not. 

What I mean is that the issue is unlikely inside of CVCalendar. If I'm mistaken try to explain it more explicitly. Hope it helps! 

Regards, 
Eugene

**Comment by marcpages** [comment]
Hello, thanks for your answer, it was my fault, I've managed to make it work. I've another question, this function:  `commitCalendarViewUpdate()`  is only for initializing the calendar or also for updating it? Because when I call it coming from another view the calendar goes wrong.

Thanks

**Comment by Mozharovsky** [comment]
Hello @marcpages, 

`commitCalendarViewUpdate()` should be called only once when your view is firstly appeared. The demo works a little bit wrong since it doesn't check whether it has been already committed an update or not. I'll update demo project and documentation with the new release. 

For now just check and ensure the method is called once. 

Regards, 
Eugene

**Comment by marcpages** [comment]
Perfect, thank you.
