### ISSUE TITLE
Returning to CVCalendar with a selected date renders day label incorrectly

### ISSUE THREAD

**Issue by jeffcardillo** [Mozharovsky/CVCalendar#22]
I am having an issue where after selecting a day (shown in blue), transition to a detail controller, and then returning back to the calendar, the selected day has the number label drawn in black on top of it. 

Running through the drawing code it appears there is a check for "current day", but not "selected day", and it is draws the regular label on top of the blue circle.

![screen shot 2015-02-20 at 5 53 25 pm](https://cloud.githubusercontent.com/assets/1125905/6310944/0a13490c-b92a-11e4-8fd7-325a8553db73.png)

**Comment by Mozharovsky** [comment]
Hello @jeffcardillo, 

The issue comes with the wrong way of CVCalendar updating. It's already been reported in issue #14, and the simplest solution is to ensure that method `commitCalendarViewUpdate()` is called once (but not on every view's appearing). 

I'll fix the documentation as soon as I have enough time for completing the new release version of CVCalendar. 

Hope it helps. 

Regards, 
Eugene

**Comment by jeffcardillo** [comment]
Perfect, thank you.
