### ISSUE TITLE
How to avoid selected day default circle being overlapped by supplementary view?

### ISSUE THREAD

**Issue by gabrielafonsogoncalves** [Mozharovsky/CVCalendar#302]
Hi,

I just want to now if there is any way to avoid the selected day circle being overlapped by  supplementary view added.?

i tried updating layer's z value like this:

`ringLayer.zPosition = -1000`

but it didn't work

Thanks in advanced.

**Comment by dustinspengler** [comment]
use:
 `func preliminaryView(shouldDisplayOnDayView dayView: DayView) -> Bool ` and 
`func preliminaryView(viewOnDayView dayView: DayView) -> UIView` 

instead of:
`func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool` and
`func supplementaryView(viewOnDayView dayView: DayView) -> UIView`
