### ISSUE TITLE
Cannot get date on didSelectDayView

### ISSUE THREAD

**Issue by rodrigoalvesvieira** [Mozharovsky/CVCalendar#41]
Hey everyone, I guess I found a bug within CVCalendar. I'm trying to use `didSelectDayView` to get the date selected by a user, but even with `if let`, I can't try to read the current date:

```swift
func didSelectDayView(dayView: CVCalendarDayView) {
    NSLog("hey ye")
    if let finalDate = dayView.date? {
        NSLog("hey ye. data final eh: ")
        println(finalDate)
}
```

This crashes the program, with the message: `Demo[12217:277145] hey ye. data final eh: 
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb)`.

It crashes when the app launches, not when I click the date. Tried this in the demo projectDoes anyone know how to solve this, please?

**Comment by Mozharovsky** [comment]
Hello @rodrigoalvesvieira, 

Thank you for reporting this issue. 

It happens because of the insecure way CVDate instances are initialized. In the very beginning day views doesn't have any associated date so you may struggle with fatal errors and crashes of your app. The upcoming release fixes that issue. If you want to use the early release version taker a look at develop branch. 

Hope it helps. 

Regards, 
Eugene
