### ISSUE TITLE
Calendar not working properly

### ISSUE THREAD

**Issue by datomnurdin** [Mozharovsky/CVCalendar#45]
I just test out your demo app, it's not working properly.

![2015-04-12 21 21 38](https://cloud.githubusercontent.com/assets/5416242/7105699/0143263e-e158-11e4-979d-4854c2ba3cf3.png)

**Comment by Mozharovsky** [comment]
Hello @datomnurdin,

Thank you for reporting that issue. The develop branch doesn't have a WeekView mode working properly at the moment. I'm doing my best to fix that issue. Or did you mean another thing? Let me know. 

Regards,
Eugene

**Comment by datomnurdin** [comment]
Noted. I think so far that's only the problem right now.

**Comment by Mozharovsky** [comment]
Hello @datomnurdin, 

WeekView mode is available now in CVCalendar. In order to get this feature use should get the code from develop branch. [<b>Hot to page</b>](https://github.com/Mozharovsky/CVCalendar/wiki/Calendar-Mode). 

Available since b4f93d6ea90a70f8a2a6e01e7b6aa1bd51fd18e2.

In case of any bugs please create a new issue. 

Regards, 
Eugene

**Comment by martjemeyer** [comment]
Nice job!
Is it only hardcoded in info.Plist, or can you change it from code? And if you choose to make two different pages, how would you setup the info.Plist file?

**Comment by Mozharovsky** [comment]
Hello @martjemeyer, 

That is a good question. I have rewritten the whole init process. Check it out here 280e067e051a2960ac7bf95d3c1235286e36f42e. Now you don't need to work with plist. Just use the delegation stuff. 

P.S. It's not finished yet. Further changes to come. 

Regards, 
Eugene

**Comment by martjemeyer** [comment]
Great!
