### ISSUE TITLE
Must call a designated initializer of the superclass 'UIView'

### ISSUE THREAD

**Issue by datomnurdin** [Mozharovsky/CVCalendar#54]
I got this error message after update my xcode to 6.3.1.

```
/Users/MNurdin/Documents/iOS/xxxxx/Pods/CVCalendar/CVCalendar/CVCalendarDayView.swift:30:9: Must call a designated initializer of the superclass 'UIView'
```

File CVCalendarDayView.swift, line number 30.

**Comment by Mozharovsky** [comment]
Hello @datomnurdin, 

The <b>master</b> branch does not support Swift 1.2. In order to get the product supporting Swift 1.2 you have to use the [pre-release version](https://github.com/Mozharovsky/CVCalendar/releases/tag/1.1.0). Note that the API hasn't been changed but now you must implement delegation protocols with two required methods for CVCalendarView and one for CVCalendarMenuView. 

Also the develop branch is still being under active maintenance so more bug fixes and new enhancements to come. Keep watching!

Regards, 
Eugene
