### ISSUE TITLE
Ability to jump to any month

### ISSUE THREAD

**Issue by thomasbaldwinj** [Mozharovsky/CVCalendar#56]
Not so much a bug, just an enhancement I thought would be cool. Maybe make a delegate method loadMonth(int monthNumber) where monthNumber is the month to switch to (i.e 0 is January and 12 is December)

**Comment by Mozharovsky** [comment]
Hello @thomasbaldwinj, 

This feature is available since the release version. All you have to do is to use a convenience method `toggleViewWithDate(date: NSDate)`. Your code may look like one below. 

```swift
    func loadDecember2015() {
        let december2015: NSDate
        // calculations with NSCalendar and NSCalendarComponents 
        // december2015 initialization 
        
        calendarView.toggleViewWithDate(december2015)
    }
```

That's it. The given code sample would work with the code in the [develop](https://github.com/Mozharovsky/CVCalendar/tree/develop) branch.

Regards, 
Eugene

**Comment by thomasbaldwinj** [comment]
Thanks a lot!
