### ISSUE TITLE
Navigating between months quickly causes program to crash

### ISSUE THREAD

**Issue by thomasbaldwinj** [Mozharovsky/CVCalendar#57]
If you're using the self.calendarView.loadNextMonth() and self.calendarView.loadPreviousMonth() methods with the navigation arrows  ("<" - to the previous, ">" - to the next), and you click them quickly enough, it causes a fatal error and the program crashes. I've attached a screenshot of it.

![screen shot 2015-04-26 at 1 37 05 pm](https://cloud.githubusercontent.com/assets/5099084/7338441/c13b0710-ec19-11e4-9aa9-752b6ba73529.png)

**Comment by Mozharovsky** [comment]
Hello @thomasbaldwinj, 

Thank you for reporting this issue. 

It's fixed in the attached commit which is available in the [develop](https://github.com/Mozharovsky/CVCalendar/tree/develop) branch. Note that there were some changes to the init process. Now you have to implement CVCalendarViewDelegate protocol and its required methods (there are only 2 which need to be implemented). Check out the demo project. 

Regards, 
Eugene

**Comment by thomasbaldwinj** [comment]
Sounds good! Thanks so much
