### ISSUE TITLE
Calendar Graphing

### ISSUE THREAD

**Issue by Trifusion** [Mozharovsky/CVCalendar#61]
Thank you for your amazing Swift Calendar code. I'd like to add a feature to encircle the dates with a ring that indicates a percentage. If you want to look quickly at my app (https://itunes.apple.com/us/app/body-pro-strength/id939864965) you will see I do this already for a single day. Having this in a calendar would allow my users to view a summary of their data like the new Apple Watch fitness app.

If you think this is a nice feature that belongs in your code I can fork yours but can you let me know how you would like it structurally coded and I will re-write my code to match yours. If you think this doesn't belong in your code I'm good with that too.

I was thinking that a good approach would be to create:
CVDayGraphData to hold the Model

create logic for showing graph in:
CVCalendarDayView

and display the graph in:
CVAuxiliaryView

and set colours for graph in:
CVCalendarViewDelegate

Let me know your thoughts

Thanks

Greg

**Comment by Mozharovsky** [comment]
Hello @Trifusion, 

Thank you for being interested in contributing into this project. 

The feature you need is a very specific for a simple calendar. But it turns out that CVCalendar doesn't provide any kind of day view customization. What I think is that day views should have supplementary views which are fully customizable. All you have to do in this way is implementing an appropriate delegation method in order to setup these supplementary views. 

I included that feature in the release goals so it will come to the project soon. I'll notify you in this thread and we can try to build what you want. 

By the way, nice app. Though alerts are a little bit annoying. Maybe it'd be better to show them only once so users won't feel the same I did closing popups I had already seen. But anyway it's cool, keep going!

Regards, 
Eugene

**Comment by Trifusion** [comment]
Thank you ... Each popup is unique but I agree can be annoying ... I added a 'Don't Show Tips' button on the popups to stop them from displaying.

I will build out my custom delegate method and a barebones CVSupplementaryView class until you get it in the project.

Greg

**Comment by Trifusion** [comment]
I wrote up a quick delegate method and got it working in the demo code and put in a pull request.

Greg

**Comment by Mozharovsky** [comment]
Hello @Trifusion, 

Thank you so much for contributing. I appreciate it a lot. The pull request is merged. :]

Regards, 
Eugene
